#include "types.h"

void initializeBoard(square *board) {
    board[0] = (square){.squareID = 0, .name = "Go", .type = go};
    board[1] = (square){

        .squareID = 1,
        .name = "Pettah",
        .type = property,
        .mortgageStatus = noMortgage,
        .mortgageValue = 750,
        .value = 1500,
        .PropertyProperties.propertyGroup = brown,
        .PropertyProperties.baseRental = 500};

    board[2] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[3] = (square){.squareID = 5,
                        .name = "Colombo Fort Railway Station",
                        .type = railway,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[4] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[5] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[6] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[7] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[8] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[9] = (square){.squareID = 2,
                        .name = "Go",
                        .type = go,
                        .owner = noOwnner,
                        .mortgageStatus = cannotMortgage,
                        .mortgageValue = 0,
                        .value = 0};
    board[10] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[11] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[12] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[13] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[14] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[15] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[16] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[17] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[18] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[19] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[20] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[21] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[22] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[23] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[24] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[25] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[26] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[27] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[28] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[29] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[30] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[31] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[32] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[33] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[34] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[35] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[36] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[37] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[38] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
    board[39] = (square){.squareID = 2,
                         .name = "Go",
                         .type = go,
                         .owner = noOwnner,
                         .mortgageStatus = cannotMortgage,
                         .mortgageValue = 0,
                         .value = 0};
}
